/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardSubcontractorsIndexRouteImport } from './routes/dashboard/subcontractors/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardHomeownersIndexRouteImport } from './routes/dashboard/homeowners/index'
import { Route as DashboardCommunicationsIndexRouteImport } from './routes/dashboard/communications/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardClientsClientIdRouteImport } from './routes/dashboard/clients/$clientId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubcontractorsIndexRoute =
  DashboardSubcontractorsIndexRouteImport.update({
    id: '/subcontractors/',
    path: '/subcontractors/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeownersIndexRoute =
  DashboardHomeownersIndexRouteImport.update({
    id: '/homeowners/',
    path: '/homeowners/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCommunicationsIndexRoute =
  DashboardCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsClientIdRoute =
  DashboardClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/communications/': typeof DashboardCommunicationsIndexRoute
  '/dashboard/homeowners/': typeof DashboardHomeownersIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/subcontractors/': typeof DashboardSubcontractorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/communications': typeof DashboardCommunicationsIndexRoute
  '/dashboard/homeowners': typeof DashboardHomeownersIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/subcontractors': typeof DashboardSubcontractorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/communications/': typeof DashboardCommunicationsIndexRoute
  '/dashboard/homeowners/': typeof DashboardHomeownersIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/subcontractors/': typeof DashboardSubcontractorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/clients/$clientId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/clients/'
    | '/dashboard/communications/'
    | '/dashboard/homeowners/'
    | '/dashboard/projects/'
    | '/dashboard/subcontractors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/clients/$clientId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/clients'
    | '/dashboard/communications'
    | '/dashboard/homeowners'
    | '/dashboard/projects'
    | '/dashboard/subcontractors'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/clients/$clientId'
    | '/dashboard/projects/$projectId'
    | '/dashboard/clients/'
    | '/dashboard/communications/'
    | '/dashboard/homeowners/'
    | '/dashboard/projects/'
    | '/dashboard/subcontractors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subcontractors/': {
      id: '/dashboard/subcontractors/'
      path: '/subcontractors'
      fullPath: '/dashboard/subcontractors/'
      preLoaderRoute: typeof DashboardSubcontractorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/homeowners/': {
      id: '/dashboard/homeowners/'
      path: '/homeowners'
      fullPath: '/dashboard/homeowners/'
      preLoaderRoute: typeof DashboardHomeownersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/communications/': {
      id: '/dashboard/communications/'
      path: '/communications'
      fullPath: '/dashboard/communications/'
      preLoaderRoute: typeof DashboardCommunicationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId': {
      id: '/dashboard/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsClientIdRoute: typeof DashboardClientsClientIdRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardCommunicationsIndexRoute: typeof DashboardCommunicationsIndexRoute
  DashboardHomeownersIndexRoute: typeof DashboardHomeownersIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardSubcontractorsIndexRoute: typeof DashboardSubcontractorsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsClientIdRoute: DashboardClientsClientIdRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardCommunicationsIndexRoute: DashboardCommunicationsIndexRoute,
  DashboardHomeownersIndexRoute: DashboardHomeownersIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardSubcontractorsIndexRoute: DashboardSubcontractorsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
